In [1]:
import numpy as np

In [2]:
#1-d array
oneDarray=np.array([1,2,3,4,5])
print(oneDarray)

[1 2 3 4 5]


In [3]:
print(oneDarray.ndim)

1


In [4]:
#two-darray
twoDarray=np.array([[1,2,3],[4,5,6]])
print(twoDarray)

[[1 2 3]
 [4 5 6]]


In [5]:
print(twoDarray.ndim)

2


In [6]:
#3-darray
threeDarray=np.array([[[1,2,3,4],[-1,-2,-3,-4]],[[4,5,6,7],[-4,-5,-6,-7]]])
print(threeDarray)

[[[ 1  2  3  4]
  [-1 -2 -3 -4]]

 [[ 4  5  6  7]
  [-4 -5 -6 -7]]]


In [7]:
threeDarray.ndim

3

In [8]:
#indexing: 1-d Numpy array is the same as indexing a 1-d python list. 
print(oneDarray[0])
print(oneDarray[2])

1
3


# 2-D Numpy Arrays

• To index a 2 D NumPy array, we provide 2 values inside the square brackets ([ ]).

• First value is the index of the inner array

• Second value is the index of the element inside the inner array

In [9]:

print(twoDarray[0,2])

3


# 3-D Numpy Arrays

• To index a 3 D NumPy array, we provide 3 values inside the square brackets ([ ]).

    • First value is the index of the inner 2 D array in the first dimension.

    • Second value is the index of the inner 1 D array in the second dimension.

    • Third value is the index of the element in the third dimension.

In [10]:
threeDarray[0,1,0]

-1

# Array Shape

• NumPy arrays have a shape attribute which returns a tuple.

• First value of the tuple gives the number of dimensions in the array.

• Second value of the tuple gives the number of elements in each dimension

In [11]:
# Array shape
print(oneDarray.shape)
print(twoDarray.shape)
print(threeDarray.shape)

(5,)
(2, 3)
(2, 2, 4)


# Iterating Over Numpy Arrays 

• We can use a for loop to iterate over a 1 D array just as we do in a 1 D Python list.

In [12]:
for i in oneDarray:
    print(i)

1
2
3
4
5


In [13]:
for i in twoDarray:
    for j in i:
        print(j)

1
2
3
4
5
6


##  Mathematics for Data Science

• NumPy provides us with a huge collection of high level functions for multi dimensional arrays.

• Let’s have a look at some of the functionality provided by NumPy.

## .zeros()

• To create a NumPy array prefilled with zeros, we can use the .zeros() built in NumPy function.


• .zeros() gives us a list prefilled with float zeros. To convert this list into integer list, we use the astype() function.

In [14]:
zeroArrays=np.zeros(10)
print(zeroArrays)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
zeroArrays=zeroArrays.astype(int)
print(zeroArrays)

[0 0 0 0 0 0 0 0 0 0]


# .ones()

• To create a NumPy array prefilled with ones, we can use the .ones() built in NumPy function.

• .ones() gives us a list prefilled with float ones. To convert this list into integer list, we use the astype function.




In [16]:
onesArray=np.ones(10)
print(onesArray)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [17]:
onesArray=onesArray.astype(int)
print(onesArray)

[1 1 1 1 1 1 1 1 1 1]


In [18]:
type(onesArray)

numpy.ndarray

In [19]:
np.__version__

'1.24.3'

In [20]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [21]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


### The Difference Between Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.



In [22]:
#copy()
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [23]:
#view()
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [25]:
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[42  2  3  4  5]


### Reshaping arrays

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2,3,2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
