In [1]:
import numpy as np

In [4]:
#1-d array
oneDarray=np.array([1,2,3,4,5])
print(oneDarray)

[1 2 3 4 5]


In [3]:
print(oneDarray.ndim)

1


In [7]:
#two-darray
twoDarray=np.array([[1,2,3],[4,5,6]])
print(twoDarray)

[[1 2 3]
 [4 5 6]]


In [6]:
print(twoDarray.ndim)

2


In [9]:
#3-darray
threeDarray=np.array([[[1,2,3,4],[-1,-2,-3,-4]],[[4,5,6,7],[-4,-5,-6,-7]]])
print(threeDarray)

[[[ 1  2  3  4]
  [-1 -2 -3 -4]]

 [[ 4  5  6  7]
  [-4 -5 -6 -7]]]


In [10]:
threeDarray.ndim

3

In [13]:
#indexing: 1-d Numpy array is the same as indexing a 1-d python list. 
print(oneDarray[0])
print(oneDarray[2])

1
3


# 2-D Numpy Arrays

• To index a 2 D NumPy array, we provide 2 values inside the square brackets ([ ]).

• First value is the index of the inner array

• Second value is the index of the element inside the inner array

In [17]:

print(twoDarray[0,2])

3


# 3-D Numpy Arrays

• To index a 3 D NumPy array, we provide 3 values inside the square brackets ([ ]).

    • First value is the index of the inner 2 D array in the first dimension.

    • Second value is the index of the inner 1 D array in the second dimension.

    • Third value is the index of the element in the third dimension.

In [18]:
threeDarray[0,1,0]

-1

# Array Shape

• NumPy arrays have a shape attribute which returns a tuple.

• First value of the tuple gives the number of dimensions in the array.

• Second value of the tuple gives the number of elements in each dimension

In [19]:
# Array shape
print(oneDarray.shape)
print(twoDarray.shape)
print(threeDarray.shape)

(5,)
(2, 3)
(2, 2, 4)


# Iterating Over Numpy Arrays 

• We can use a for loop to iterate over a 1 D array just as we do in a 1 D Python list.

In [20]:
for i in oneDarray:
    print(i)

1
2
3
4
5


In [24]:
for i in twoDarray:
    for j in i:
        print(j)

1
2
3
4
5
6


##  Mathematics for Data Science

• NumPy provides us with a huge collection of high level functions for multi dimensional arrays.

• Let’s have a look at some of the functionality provided by NumPy.

## .zeros()

• To create a NumPy array prefilled with zeros, we can use the .zeros() built in NumPy function.


• .zeros() gives us a list prefilled with float zeros. To convert this list into integer list, we use the astype() function.

In [25]:
zeroArrays=np.zeros(10)
print(zeroArrays)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [26]:
zeroArrays=zeroArrays.astype(int)
print(zeroArrays)

[0 0 0 0 0 0 0 0 0 0]


# .ones()

• To create a NumPy array prefilled with ones, we can use the .ones() built in NumPy function.

• .ones() gives us a list prefilled with float ones. To convert this list into integer list, we use the astype function.




In [27]:
onesArray=np.ones(10)
print(onesArray)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [29]:
onesArray=onesArray.astype(int)
print(onesArray)

[1 1 1 1 1 1 1 1 1 1]
