# NumPy quickstart

## Prerequisites

You’ll need to know a bit of Python. For a refresher, see the 0.1 Python tutorial.

To work the examples, you’ll need matplotlib installed in addition to NumPy.
if not installed try installing using this code "!pip install matplotlib"

In [1]:
# To access NumPy and its functions import it in your Python code like this:
import numpy as np

### Why use NumPy?

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

### What is an array?

An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the **array dtype**.

One way we can initialize NumPy arrays is from Python lists, using nested lists for two- or higher-dimensional data.

In [2]:
a=np.array([0,1,2,3,4])

You might occasionally hear an array referred to as a “ndarray,” which is shorthand for “N-dimensional array.” 

An N-dimensional array is simply an array with any number of dimensions. 

You might also hear 1-D, or one-dimensional array, 2-D, or two-dimensional array, and so on. 

The NumPy ndarray class is used to represent both matrices and vectors. 

A vector is an array with a single dimension (there’s no difference between row and column vectors),

while a matrix refers to an array with two dimensions. 

For 3-D or higher dimensional arrays, the term tensor is also commonly used.

In [3]:
type(a)

numpy.ndarray

We can access the elements in the array using square brackets. 

When you’re accessing elements, remember that indexing in NumPy starts at 0. That means that if you want to access the first element in your array, you’ll be accessing element “0”.

In [4]:
print(a[0])

0


### What are the attributes of an array?

An array is usually a fixed-size container of items of the same type and size. 

The number of dimensions and items in an array is defined by its shape. 

The shape of an array is a tuple of non-negative integers that specify the sizes of each dimension.

In NumPy, dimensions are called axes. This means that if you have a 2D array that looks like this:

In [8]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b.shape

(3, 4)

Your array has 2 axes. The first axis(Row) has a length of 3 and the second axis(Column) has a length of 4.

# How to create a basic array

1. To create a NumPy array, you can use the function np.array().

All you need to do to create a simple array is pass a list to it. If you choose to, you can also specify the type of data in your list.

In [9]:
c=np.array([2,3,4,5,6])

Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s:

In [10]:
d=np.zeros(2)
d

array([0., 0.])

Or an array filled with 1’s:

In [12]:
e=np.ones(5)
e

array([1., 1., 1., 1., 1.])

Or even an empty array! 

The function empty creates an array whose initial content is random and depends on the state of the memory. 

The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

In [13]:
f=np.empty(5)
f

array([1., 1., 1., 1., 1.])

You can create an array with a range of elements:

In [15]:
g=np.arange(5)
g

array([0, 1, 2, 3, 4])

And even an array that contains a range of evenly spaced intervals. 

To do this, you will specify the first number, last number, and the step size.

In [16]:
h=np.arange(2,9,2)
h

array([2, 4, 6, 8])

You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:

In [17]:
i=np.linspace(10,15,num=5)
i

array([10.  , 11.25, 12.5 , 13.75, 15.  ])

### Specifying your data type

While the default data type is floating point (np.float64), you can explicitly specify which data type you want using the dtype keyword.

In [18]:
j=np.ones(5,dtype=np.int64)
j

array([1, 1, 1, 1, 1], dtype=int64)

# Adding, removing, and sorting elements

Sorting an element is simple with np.sort(). You can specify the axis, kind, and order when you call the function.

In [20]:
arr=np.array([9,8,5,4,1,2,7,6,3])
arr


array([9, 8, 5, 4, 1, 2, 7, 6, 3])

In [21]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

If you start with these arrays:

In [22]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

You can concatenate them with np.concatenate()

In [24]:
c=np.concatenate((a,b), axis=0)
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [29]:
z=np.concatenate((x,y), axis=0)
z

array([[1, 2],
       [3, 4],
       [5, 6]])

# How do you know the shape and size of an array?

**ndarray.ndim** will tell you the number of axes, or dimensions, of the array.

**ndarray.size** will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

**ndarray.shape** will display a tuple of integers that indicate the number of elements stored along each dimension of the array. 

If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [30]:
z.ndim

2

In [31]:
z.size

6

In [32]:
z.shape

(3, 2)

# Can you reshape an array?

Yes!

Using arr.reshape() will give a new shape to an array without changing the data. 

Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. 

If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

If you start with this array:

In [33]:
d=np.arange(10)
print(d)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
b=d.reshape(5,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])