# NumPy quickstart

## Prerequisites

You’ll need to know a bit of Python. For a refresher, see the 0.1 Python tutorial.

To work the examples, you’ll need matplotlib installed in addition to NumPy.
if not installed try installing using this code "!pip install matplotlib"

In [1]:
# To access NumPy and its functions import it in your Python code like this:
import numpy as np

### Why use NumPy?

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

### What is an array?

An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the **array dtype**.

One way we can initialize NumPy arrays is from Python lists, using nested lists for two- or higher-dimensional data.

In [2]:
a=np.array([0,1,2,3,4])

You might occasionally hear an array referred to as a “ndarray,” which is shorthand for “N-dimensional array.” 

An N-dimensional array is simply an array with any number of dimensions. 

You might also hear 1-D, or one-dimensional array, 2-D, or two-dimensional array, and so on. 

The NumPy ndarray class is used to represent both matrices and vectors. 

A vector is an array with a single dimension (there’s no difference between row and column vectors),

while a matrix refers to an array with two dimensions. 

For 3-D or higher dimensional arrays, the term tensor is also commonly used.

In [3]:
type(a)

numpy.ndarray

We can access the elements in the array using square brackets. 

When you’re accessing elements, remember that indexing in NumPy starts at 0. That means that if you want to access the first element in your array, you’ll be accessing element “0”.

In [4]:
print(a[0])

0


### What are the attributes of an array?

An array is usually a fixed-size container of items of the same type and size. 

The number of dimensions and items in an array is defined by its shape. 

The shape of an array is a tuple of non-negative integers that specify the sizes of each dimension.

In NumPy, dimensions are called axes. This means that if you have a 2D array that looks like this:

In [8]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b.shape

(3, 4)

Your array has 2 axes. The first axis(Row) has a length of 3 and the second axis(Column) has a length of 4.

# How to create a basic array

1. To create a NumPy array, you can use the function np.array().

All you need to do to create a simple array is pass a list to it. If you choose to, you can also specify the type of data in your list.

In [9]:
c=np.array([2,3,4,5,6])

Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s:

In [10]:
d=np.zeros(2)
d

array([0., 0.])

Or an array filled with 1’s:

In [12]:
e=np.ones(5)
e

array([1., 1., 1., 1., 1.])

Or even an empty array! 

The function empty creates an array whose initial content is random and depends on the state of the memory. 

The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

In [13]:
f=np.empty(5)
f

array([1., 1., 1., 1., 1.])

You can create an array with a range of elements:

In [15]:
g=np.arange(5)
g

array([0, 1, 2, 3, 4])

And even an array that contains a range of evenly spaced intervals. 

To do this, you will specify the first number, last number, and the step size.

In [16]:
h=np.arange(2,9,2)
h

array([2, 4, 6, 8])

You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:

In [17]:
i=np.linspace(10,15,num=5)
i

array([10.  , 11.25, 12.5 , 13.75, 15.  ])

### Specifying your data type

While the default data type is floating point (np.float64), you can explicitly specify which data type you want using the dtype keyword.

In [18]:
j=np.ones(5,dtype=np.int64)
j

array([1, 1, 1, 1, 1], dtype=int64)

# Adding, removing, and sorting elements

Sorting an element is simple with np.sort(). You can specify the axis, kind, and order when you call the function.

In [20]:
arr=np.array([9,8,5,4,1,2,7,6,3])
arr


array([9, 8, 5, 4, 1, 2, 7, 6, 3])

In [21]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

If you start with these arrays:

In [22]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

You can concatenate them with np.concatenate()

In [24]:
c=np.concatenate((a,b), axis=0)
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [29]:
z=np.concatenate((x,y), axis=0)
z

array([[1, 2],
       [3, 4],
       [5, 6]])

# How do you know the shape and size of an array?

**ndarray.ndim** will tell you the number of axes, or dimensions, of the array.

**ndarray.size** will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

**ndarray.shape** will display a tuple of integers that indicate the number of elements stored along each dimension of the array. 

If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [30]:
z.ndim

2

In [31]:
z.size

6

In [32]:
z.shape

(3, 2)

# Can you reshape an array?

Yes!

Using arr.reshape() will give a new shape to an array without changing the data. 

Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. 

If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

If you start with this array:

In [33]:
d=np.arange(10)
print(d)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
b=d.reshape(5,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# How to convert a 1D array into a 2D array (how to add a new axis to an array)

You can use np.newaxis and np.expand_dims to increase the dimensions of your existing array.

Using **np.newaxis** will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

In [36]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [38]:
a2=a[np.newaxis,:]
a2

array([[1, 2, 3, 4, 5, 6]])

You can explicitly convert a 1D array to either a row vector or a column vector using np.newaxis. 

For example, you can convert a 1D array to a row vector by inserting an axis along the first dimension:

In [42]:
row_vector = a[np.newaxis,:]
print(row_vector)
row_vector.shape 

[[1 2 3 4 5 6]]


(1, 6)

In [41]:
col_vector=a[:,np.newaxis]
print(col_vector)
col_vector.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

You can also expand an array by inserting a new axis at a specified position with np.expand_dims.

In [43]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [44]:
b=np.expand_dims(a,axis=1)
print(b)
b.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

In [45]:
c=np.expand_dims(a,axis=0)
print(c)
c.shape

[[1 2 3 4 5 6]]


(1, 6)

# Indexing and slicing

You can index and slice NumPy arrays in the same ways you can slice Python lists.

In [46]:
data = np.array([1, 2, 3])
data[1]

2

In [47]:
data[0:2]

array([1, 2])

In [48]:
data[:]

array([1, 2, 3])

In [49]:
data[1:]

array([2, 3])

In [50]:
data[-2:]

array([2, 3])

If you want to select values from your array that fulfill certain conditions, it’s straightforward with NumPy.

For example, if you start with this array:

In [51]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [52]:
print(a[a<6])

[1 2 3 4 5]


You can also select, for example, numbers that are equal to or greater than 5, and use that condition to index an array.

In [53]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


You can select elements that are divisible by 2:

In [55]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


Or you can select elements that satisfy two conditions using the & and | operators:

In [56]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [57]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


You can also use np.nonzero() to select elements or indices from an array.

Starting with this array:

In [58]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

You can use np.nonzero() to print the indices of elements that are, for example, less than 5:

In [59]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In this example, a tuple of arrays was returned: one for each dimension. 

The first array represents the row indices where these values are found, and the second array represents the column indices where the values are found.

If you want to generate a list of coordinates where the elements exist, you can zip the arrays, iterate over the list of coordinates, and print them. For example:

In [60]:
list_of_coordinates= list(zip(b[0], b[1]))

In [61]:
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


You can also use np.nonzero() to print the elements in an array that are less than 5 with.

In [62]:
print(a[b])

[1 2 3 4]


If the element you’re looking for doesn’t exist in the array, then the returned array of indices will be empty. For example:

In [63]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


# How to create an array from existing data

You can easily create a new array from a section of an existing array.

Let’s say you have this array:

In [64]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

You can create a new array from a section of your array any time by specifying where you want to slice your array.

In [65]:
arr1=a[3:8]

In [66]:
arr1

array([4, 5, 6, 7, 8])

Here, you grabbed a section of your array from index position 3 through index position 8.

You can also stack two existing arrays, both vertically and horizontally. Let’s say you have two arrays, a1 and a2:

In [67]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

You can stack them vertically with vstack:

In [68]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

Or stack them horizontally with hstack:

In [70]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

You can split an array into several smaller arrays using hsplit. 

You can specify either the number of equally shaped arrays to return or the columns after which the division should occur.

Let’s say you have this array:

In [71]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

If you wanted to split this array into three equally shaped arrays, you would run:

In [72]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

If you wanted to split your array after the third and fourth column, you’d run:

In [74]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

You can use the view method to create a new array object that looks at the same data as the original array (a shallow copy).

Views are an important NumPy concept! NumPy functions, as well as operations like indexing and slicing, will return views whenever possible. 

This saves memory and is faster (no copy of the data has to be made). However it’s important to be aware of this - modifying data in a view also modifies the original array!

Let’s say you create this array:

In [82]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [83]:
b=a.view()

In [84]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [85]:
b[0][1]=4

In [86]:
print(a)
print(b)

[[ 1  4  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  4  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Using the copy method will make a complete copy of the array and its data (a deep copy). To use this on your array, you could run:

In [87]:
b2 = a.copy()

In [89]:
b2[0][1]=2

In [90]:
b2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [91]:
a

array([[ 1,  4,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Basic array operations

Once you’ve created your arrays, you can start to work with them. 

Let’s say, for example, that you’ve created two arrays, one called “data” and one called “ones”

In [92]:
data = np.array([1, 2])

In [93]:
ones = np.ones(2, dtype=int)

In [94]:
data + ones

array([2, 3])

In [95]:
data-ones

array([0, 1])

In [96]:
data*ones

array([1, 2])

In [97]:
data/data

array([1., 1.])

Basic operations are simple with NumPy.
 
If you want to find the sum of the elements in an array, you’d use sum(). 

This works for 1D arrays, 2D arrays, and arrays in higher dimensions.

In [98]:
a = np.array([1, 2, 3, 4])

In [99]:
a.sum()

10

To add the rows or the columns in a 2D array, you would specify the axis.

If you start with this array:

In [100]:
b = np.array([[1, 1], [2, 2]])

In [103]:
b.sum(axis=0)

array([3, 3])

In [104]:
b.sum(axis=1)

array([2, 4])

# Broadcasting

There are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes. 

For example, your array (we’ll call it “data”) might contain information about distance in miles but you want to convert the information to kilometers. You can perform this operation with:

In [105]:
data = np.array([1.0, 2.0])

In [106]:
data*1.6

array([1.6, 3.2])

NumPy understands that the multiplication should happen with each cell. 

That concept is called broadcasting. Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes. 

The dimensions of your array must be compatible, for example, when the dimensions of both arrays are equal or when one of them is 1. 

If the dimensions are not compatible, you will get a ValueError.

# More useful array operations

NumPy also performs aggregation functions.

 In addition to min, max, and sum, you can easily run mean to get the average, prod to get the result of multiplying the elements together, std to get the standard deviation, and more.