# NumPy quickstart

## Prerequisites

You’ll need to know a bit of Python. For a refresher, see the 0.1 Python tutorial.

To work the examples, you’ll need matplotlib installed in addition to NumPy.
if not installed try installing using this code "!pip install matplotlib"

In [1]:
# To access NumPy and its functions import it in your Python code like this:
import numpy as np

### Why use NumPy?

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

### What is an array?

An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the **array dtype**.

One way we can initialize NumPy arrays is from Python lists, using nested lists for two- or higher-dimensional data.

In [2]:
a=np.array([0,1,2,3,4])

You might occasionally hear an array referred to as a “ndarray,” which is shorthand for “N-dimensional array.” 

An N-dimensional array is simply an array with any number of dimensions. 

You might also hear 1-D, or one-dimensional array, 2-D, or two-dimensional array, and so on. 

The NumPy ndarray class is used to represent both matrices and vectors. 

A vector is an array with a single dimension (there’s no difference between row and column vectors),

while a matrix refers to an array with two dimensions. 

For 3-D or higher dimensional arrays, the term tensor is also commonly used.

In [3]:
type(a)

numpy.ndarray

We can access the elements in the array using square brackets. 

When you’re accessing elements, remember that indexing in NumPy starts at 0. That means that if you want to access the first element in your array, you’ll be accessing element “0”.

In [4]:
print(a[0])

0


### What are the attributes of an array?

An array is usually a fixed-size container of items of the same type and size. 

The number of dimensions and items in an array is defined by its shape. 

The shape of an array is a tuple of non-negative integers that specify the sizes of each dimension.

In NumPy, dimensions are called axes. This means that if you have a 2D array that looks like this:

In [8]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b.shape

(3, 4)

Your array has 2 axes. The first axis(Row) has a length of 3 and the second axis(Column) has a length of 4.

# How to create a basic array

1. To create a NumPy array, you can use the function np.array().

All you need to do to create a simple array is pass a list to it. If you choose to, you can also specify the type of data in your list.

In [9]:
c=np.array([2,3,4,5,6])

Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s:

In [10]:
d=np.zeros(2)
d

array([0., 0.])

Or an array filled with 1’s:

In [12]:
e=np.ones(5)
e

array([1., 1., 1., 1., 1.])

Or even an empty array! 

The function empty creates an array whose initial content is random and depends on the state of the memory. 

The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

In [13]:
f=np.empty(5)
f

array([1., 1., 1., 1., 1.])

You can create an array with a range of elements:

In [15]:
g=np.arange(5)
g

array([0, 1, 2, 3, 4])

And even an array that contains a range of evenly spaced intervals. 

To do this, you will specify the first number, last number, and the step size.

In [16]:
h=np.arange(2,9,2)
h

array([2, 4, 6, 8])

You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:

In [17]:
i=np.linspace(10,15,num=5)
i

array([10.  , 11.25, 12.5 , 13.75, 15.  ])

### Specifying your data type

While the default data type is floating point (np.float64), you can explicitly specify which data type you want using the dtype keyword.

In [18]:
j=np.ones(5,dtype=np.int64)
j

array([1, 1, 1, 1, 1], dtype=int64)

# Adding, removing, and sorting elements

Sorting an element is simple with np.sort(). You can specify the axis, kind, and order when you call the function.

In [20]:
arr=np.array([9,8,5,4,1,2,7,6,3])
arr


array([9, 8, 5, 4, 1, 2, 7, 6, 3])

In [21]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

If you start with these arrays:

In [22]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

You can concatenate them with np.concatenate()

In [24]:
c=np.concatenate((a,b), axis=0)
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [29]:
z=np.concatenate((x,y), axis=0)
z

array([[1, 2],
       [3, 4],
       [5, 6]])

# How do you know the shape and size of an array?

**ndarray.ndim** will tell you the number of axes, or dimensions, of the array.

**ndarray.size** will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

**ndarray.shape** will display a tuple of integers that indicate the number of elements stored along each dimension of the array. 

If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [30]:
z.ndim

2

In [31]:
z.size

6

In [32]:
z.shape

(3, 2)

# Can you reshape an array?

Yes!

Using arr.reshape() will give a new shape to an array without changing the data. 

Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. 

If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

If you start with this array:

In [33]:
d=np.arange(10)
print(d)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
b=d.reshape(5,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# How to convert a 1D array into a 2D array (how to add a new axis to an array)

You can use np.newaxis and np.expand_dims to increase the dimensions of your existing array.

Using **np.newaxis** will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

In [36]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [38]:
a2=a[np.newaxis,:]
a2

array([[1, 2, 3, 4, 5, 6]])

You can explicitly convert a 1D array to either a row vector or a column vector using np.newaxis. 

For example, you can convert a 1D array to a row vector by inserting an axis along the first dimension:

In [42]:
row_vector = a[np.newaxis,:]
print(row_vector)
row_vector.shape 

[[1 2 3 4 5 6]]


(1, 6)

In [41]:
col_vector=a[:,np.newaxis]
print(col_vector)
col_vector.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

You can also expand an array by inserting a new axis at a specified position with np.expand_dims.

In [43]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [44]:
b=np.expand_dims(a,axis=1)
print(b)
b.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

In [45]:
c=np.expand_dims(a,axis=0)
print(c)
c.shape

[[1 2 3 4 5 6]]


(1, 6)

# Indexing and slicing

You can index and slice NumPy arrays in the same ways you can slice Python lists.

In [46]:
data = np.array([1, 2, 3])
data[1]

2

In [47]:
data[0:2]

array([1, 2])

In [48]:
data[:]

array([1, 2, 3])

In [49]:
data[1:]

array([2, 3])

In [50]:
data[-2:]

array([2, 3])

If you want to select values from your array that fulfill certain conditions, it’s straightforward with NumPy.

For example, if you start with this array:

In [51]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [52]:
print(a[a<6])

[1 2 3 4 5]


You can also select, for example, numbers that are equal to or greater than 5, and use that condition to index an array.

In [53]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


You can select elements that are divisible by 2:

In [55]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


Or you can select elements that satisfy two conditions using the & and | operators:

In [56]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [57]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


You can also use np.nonzero() to select elements or indices from an array.

Starting with this array:

In [58]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

You can use np.nonzero() to print the indices of elements that are, for example, less than 5:

In [59]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In this example, a tuple of arrays was returned: one for each dimension. 

The first array represents the row indices where these values are found, and the second array represents the column indices where the values are found.

If you want to generate a list of coordinates where the elements exist, you can zip the arrays, iterate over the list of coordinates, and print them. For example:

In [60]:
list_of_coordinates= list(zip(b[0], b[1]))

In [61]:
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


You can also use np.nonzero() to print the elements in an array that are less than 5 with.

In [62]:
print(a[b])

[1 2 3 4]


If the element you’re looking for doesn’t exist in the array, then the returned array of indices will be empty. For example:

In [63]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


# How to create an array from existing data

You can easily create a new array from a section of an existing array.

Let’s say you have this array:

In [64]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

You can create a new array from a section of your array any time by specifying where you want to slice your array.

In [65]:
arr1=a[3:8]

In [66]:
arr1

array([4, 5, 6, 7, 8])

Here, you grabbed a section of your array from index position 3 through index position 8.

You can also stack two existing arrays, both vertically and horizontally. Let’s say you have two arrays, a1 and a2:

In [67]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

You can stack them vertically with vstack:

In [68]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

Or stack them horizontally with hstack:

In [70]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

You can split an array into several smaller arrays using hsplit. 

You can specify either the number of equally shaped arrays to return or the columns after which the division should occur.

Let’s say you have this array:

In [71]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

If you wanted to split this array into three equally shaped arrays, you would run:

In [72]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

If you wanted to split your array after the third and fourth column, you’d run:

In [74]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

You can use the view method to create a new array object that looks at the same data as the original array (a shallow copy).

Views are an important NumPy concept! NumPy functions, as well as operations like indexing and slicing, will return views whenever possible. 

This saves memory and is faster (no copy of the data has to be made). However it’s important to be aware of this - modifying data in a view also modifies the original array!

Let’s say you create this array:

In [82]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [83]:
b=a.view()

In [84]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [85]:
b[0][1]=4

In [86]:
print(a)
print(b)

[[ 1  4  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  4  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Using the copy method will make a complete copy of the array and its data (a deep copy). To use this on your array, you could run:

In [87]:
b2 = a.copy()

In [89]:
b2[0][1]=2

In [90]:
b2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [91]:
a

array([[ 1,  4,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Basic array operations

Once you’ve created your arrays, you can start to work with them. 

Let’s say, for example, that you’ve created two arrays, one called “data” and one called “ones”

In [92]:
data = np.array([1, 2])

In [93]:
ones = np.ones(2, dtype=int)

In [94]:
data + ones

array([2, 3])

In [95]:
data-ones

array([0, 1])

In [96]:
data*ones

array([1, 2])

In [97]:
data/data

array([1., 1.])

Basic operations are simple with NumPy.
 
If you want to find the sum of the elements in an array, you’d use sum(). 

This works for 1D arrays, 2D arrays, and arrays in higher dimensions.

In [98]:
a = np.array([1, 2, 3, 4])

In [99]:
a.sum()

10

To add the rows or the columns in a 2D array, you would specify the axis.

If you start with this array:

In [100]:
b = np.array([[1, 1], [2, 2]])

In [103]:
b.sum(axis=0)

array([3, 3])

In [104]:
b.sum(axis=1)

array([2, 4])

# Broadcasting

There are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes. 

For example, your array (we’ll call it “data”) might contain information about distance in miles but you want to convert the information to kilometers. You can perform this operation with:

In [105]:
data = np.array([1.0, 2.0])

In [106]:
data*1.6

array([1.6, 3.2])

NumPy understands that the multiplication should happen with each cell. 

That concept is called broadcasting. Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes. 

The dimensions of your array must be compatible, for example, when the dimensions of both arrays are equal or when one of them is 1. 

If the dimensions are not compatible, you will get a ValueError.

# More useful array operations

NumPy also performs aggregation functions.

 In addition to min, max, and sum, you can easily run mean to get the average, prod to get the result of multiplying the elements together, std to get the standard deviation, and more.

In [107]:
data.min()

1.0

In [108]:
data.max()

2.0

In [109]:
data.sum()

3.0

Let’s start with this array, called “a”

In [110]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

It’s very common to want to aggregate along a row or column. 

By default, every NumPy aggregation function will return the aggregate of the entire array. 

To find the sum or the minimum of the elements in your array, run:

In [111]:
a.sum()

4.8595784

In [112]:
a.min()

0.05093587

You can specify on which axis you want the aggregation function to be computed. For example, you can find the minimum value within each column by specifying axis=0.

In [113]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

The four values listed above correspond to the number of columns in your array. With a four-column array, you will get four values as your result.

# Creating matrices

You can pass Python lists of lists to create a 2-D array (or “matrix”) to represent them in NumPy.

In [115]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

Indexing and slicing operations are useful when you’re manipulating matrices:

In [116]:
data[0,1]

2

In [117]:
data[0:2, 0]

array([1, 3])

You can aggregate matrices the same way you aggregated vectors:

In [118]:
data.min()

1

In [119]:
data.max()

6

In [120]:
data.sum()

21

You can aggregate all the values in a matrix and you can aggregate them across columns or rows using the axis parameter.

To illustrate this point, let’s look at a slightly modified dataset:

In [121]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [122]:
data.max(axis=0)

array([5, 6])

In [123]:
data.max(axis=1)

array([2, 5, 6])

Once you’ve created your matrices, you can add and multiply them using arithmetic operators if you have two matrices that are the same size.

In [124]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

You can do these arithmetic operations on matrices of different sizes, but only if one matrix has only one column or one row. In this case, NumPy will use its broadcast rules for the operation.

In [125]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [127]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

There are often instances where we want NumPy to initialize the values of an array. 

NumPy offers functions like ones() and zeros(), and the random.Generator class for random number generation for that. 

All you need to do is pass in the number of elements you want it to generate:

In [128]:
np.ones(2)

array([1., 1.])

In [129]:
np.zeros(2)

array([0., 0.])

In [130]:
rng=np.random.default_rng()
rng.random(3)

array([0.84717998, 0.27526814, 0.48141675])

You can also use ones(), zeros(), and random() to create a 2D array if you give them a tuple describing the dimensions of the matrix:

In [131]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [132]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [134]:
rng.random((3,2))

array([[0.27138922, 0.67112016],
       [0.76099004, 0.69142298],
       [0.00913631, 0.40553734]])

# Generating random numbers

The use of random number generation is an important part of the configuration and evaluation of many numerical and machine learning algorithms. 

Whether you need to randomly initialize weights in an artificial neural network, split data into random sets, or randomly shuffle your dataset, being able to generate random numbers (actually, repeatable pseudo-random numbers) is essential.

With **Generator.integers**, you can generate random integers from low (remember that this is inclusive with NumPy) to high (exclusive).

You can set **endpoint=True** to make the high number inclusive.

You can generate a 2 x 4 array of random integers between 0 and 4 with:

In [135]:
rng.integers(5,size=(4,2))

array([[3, 1],
       [0, 3],
       [3, 3],
       [0, 3]], dtype=int64)

# How to get unique items and counts

You can find the unique elements in an array easily with np.unique.

For example, if you start with this array:

In [136]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [137]:
unique_values=np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


To get the indices of unique values in a NumPy array (an array of first index positions of unique values in the array), just pass the **return_index** argument in np.unique() as well as your array.

In [138]:
unique_values, indeices=np.unique(a, return_index=True)
print(indeices)

[ 0  2  3  4  5  6  7 12 13 14]


You can pass the return_counts argument in np.unique() along with your array to get the frequency count of unique values in a NumPy array.

In [140]:
unique_values, counts=np.unique(a, return_counts=True)
print(unique_values, ":" ,counts )

[11 12 13 14 15 16 17 18 19 20] : [3 2 2 2 1 1 1 1 1 1]


This also works with 2D arrays! If you start with this array:

In [141]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [142]:
np.unique(a_2d)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

If the axis argument isn’t passed, your 2D array will be flattened.

If you want to get the unique rows or columns, make sure to pass the axis argument. To find the unique rows, specify axis=0 and for columns, specify axis=1.

In [144]:
uniq_rows=np.unique(a_2d, axis=0)
uniq_rows

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

To get the unique rows, index position, and occurrence count, you can use:

In [145]:
uniq_rows,indeices,counts=np.unique(a_2d,axis=0,return_counts=True,return_index=True)

In [146]:
counts

array([2, 1, 1], dtype=int64)

In [147]:
indeices

array([0, 1, 2], dtype=int64)

# Transposing and reshaping a matrix

It’s common to need to transpose your matrices. NumPy arrays have the property T that allows you to transpose a matrix.

You may also need to switch the dimensions of a matrix. 

This can happen when, for example, you have a model that expects a certain input shape that is different from your dataset. 

This is where the reshape method can be useful. You simply need to pass in the new dimensions that you want for the matrix.

In [149]:
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [150]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

You can also use .transpose() to reverse or change the axes of an array according to the values you specify.

If you start with this array:

In [151]:
arr=np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

You can transpose your array with arr.transpose().

In [152]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

You can also use arr.T:

In [153]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

# How to reverse an array

NumPy’s np.flip() function allows you to flip, or reverse, the contents of an array along an axis. 

When using np.flip(), specify the array you would like to reverse and the axis. If you don’t specify the axis, NumPy will reverse the contents along all of the axes of your input array.

Reversing a 1D array

If you begin with a 1D array like this one:

In [154]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

You can reverse it with:

In [155]:
reversed_arr=np.flip(arr)

If you want to print your reversed array, you can run:

In [157]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


# Reversing a 2D array

A 2D array works much the same way.

If you start with this array:

In [158]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

You can reverse the content in all of the rows and all of the columns with:

In [159]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


You can easily reverse only the rows with:

In [160]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [161]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


You can also reverse the contents of only one column or row. 

For example, you can reverse the contents of the row at index position 1 (the second row):

In [162]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


You can also reverse the column at index position 1 (the second column):

In [163]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


# Reshaping and flattening multidimensional arrays

There are two popular ways to flatten an array: .flatten() and .ravel(). 

The primary difference between the two is that the new array created using ravel() is actually a reference to the parent array (i.e., a “view”). 

This means that any changes to the new array will affect the parent array as well. 

Since ravel does not create a copy, it’s memory efficient.

If you start with this array:

In [164]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

You can use flatten to flatten your array into a 1D array.

In [165]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

When you use flatten, changes to your new array won’t change the parent array.

For example:



In [167]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array
print(a1)  # New array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


But when you use ravel, the changes you make to the new array will affect the parent array.

For example:

In [169]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array
print(a2)  # New array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]


# How to save and load NumPy objects

* You will, at some point, want to save your arrays to disk and load them back without having to re-run the code. Fortunately, there are several ways to save and load objects with NumPy. 

* The ndarray objects can be saved to and loaded from the disk files with **loadtxt** and **savetxt** functions that handle normal text files, load and save functions that handle NumPy binary files with a **.npy** file extension, and a savez function that handles NumPy files with a **.npz** file extension.

* The .npy and **.npz** files store data, shape, dtype, and other information required to reconstruct the ndarray in a way that allows the array to be correctly retrieved, even when the file is on another machine with different architecture.

* If you want to store a single ndarray object, store it as a **.npy** file using **np.save**. If you want to store more than one ndarray object in a single file, save it as a **.npz** file using np.savez. 

* You can also save several arrays into a single file in compressed npz format with savez_compressed.



* It’s easy to save and load and array with np.save(). Just make sure to specify the array you want to save and a file name. For example, if you create this array:

In [170]:
a = np.array([1, 2, 3, 4, 5, 6])

You can save it as “filename.npy” with:

In [171]:
np.save('numpython.npy',a)

You can use np.load() to reconstruct your array.

In [172]:
b=np.load('numpython.npy')

If you want to check your array, you can run:

In [173]:
b

array([1, 2, 3, 4, 5, 6])

You can save a NumPy array as a plain text file like a .csv or .txt file with np.savetxt.

For example, if you create this array:

In [174]:
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

You can easily save it as a .csv file with the name “new_file.csv” like this:

In [175]:
np.savetxt("numpy.csv", csv_arr)

In [177]:
cn=np.loadtxt('numpy.csv')

In [178]:
cn

array([1., 2., 3., 4., 5., 6., 7., 8.])